{% set name = "gidgethub" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1ebe79cf80ad64cb78c880efc7f30ac664e18b80dfd18ee201bf8685cf029628

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
    - pytest-runner
  run:
    - python >=3.6
    - uritemplate >=3.0.0

test:
  imports:
    - gidgethub
    - gidgethub.test

about:
  home: https://gidgethub.readthedocs.io/en/latest/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'An async GitHub API library for Python'

  doc_url: https://gidgethub.readthedocs.io/en/latest/
  dev_url: https://github.com/brettcannon/gidgethub

extra:
  recipe-maintainers:
    - asmeurer
