travis:
  secure:
    BINSTAR_TOKEN: TYfqMzswEb4xuojHuiqtc5poX+Zyygo8vNVsFYEvNeqmwlGMeuDx3YSwgPxab42ZtazhVFG98FejnvJt6r2J8GKRQXACthtllEwTVlDh1BUgsw6KxY2GP/U+uAer/w1R0R3DOg5Zt0jZflUjTsXmTcN1zHV0S18iYEuoUBIHwQXOqOP7r7s4f5wJJX+A05oGiJaC6SPknVOhZeAwDtgiOv3jW1bCFLAPfDgrJ4uTiougmH10/VaZxoFZoj5loXGsxfWuiYOmyEkTWJS1fSLROPEVcHs+XzojAtPjt4vjnNo5RbRrioJCDTO3+XP6irf1Y2GxgbHE25ohM9g/pM5V12qaWyFSJx3/jQCJIsC54TzkGSPUR3bokMPsOKIe7f6Ieod6C+RRDWyWyCz1R2LmWmIWenu0NWogYBmIeacMiekqLEEZnHMUFtTciBgVimNh9x7yOsM/G22t6DExZ9acUyzE+HkbiYLRkHVKU3wTMw0u99VpuEVBaH0zO4omBIF3E6fHUThVaa9+WQe05EWdyXVmaWTqgdJshnAUfDST+rWsFStZcb2Hzwtim13xirJMdXjLrrKjohM24JIrI2VVQeDNPSVWDWTsg9BO2TU4zpO1qUs3Du9mUOPVtXbYfpC2sUpXkDN62ogx4P5zTHGb9kSX9PSkM5gaE7kUm1MmQ+U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
